name: Build RamaSoft S3
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install PlatformIO
        run: pip install platformio
      - name: Build
        run: pio run -e esp32-s3-devkitc-1-psram
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: RamaSoft-S3
          path: |
            .pio/build/esp32-s3-devkitc-1-psram/firmware.bin
            .pio/build/esp32-s3-devkitc-1-psram/bootloader.bin
            .pio/build/esp32-s3-devkitc-1-psram/partitions.bin
